run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic
    - gosec
    - revive
  disable:
    - unused  # Too strict for helper functions

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  revive:
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
        disabled: true
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
      - name: superfluous-else
      - name: unreachable-code

  gosec:
    excludes:
      - G204  # Subprocess launched with variable - we need this for shell commands
      - G304  # File path provided as taint input - we need this for user file paths
      - G301  # Directory permissions - 0750 is reasonable for cache/config dirs
      - G302  # File permissions - 0600 for regular files is reasonable
      - G306  # File permissions - 0600 for config files is reasonable
      - G101  # False positive on token variable names

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
