package app

import (
	"fmt"
	"time"

	"github.com/blackwell-systems/shelfctl/internal/catalog"
	"github.com/blackwell-systems/shelfctl/internal/operations"
)

// generateShelfREADME creates a README.md template for a new shelf
func generateShelfREADME(shelfName, repoName, owner string) string {
	now := time.Now().Format("2006-01-02")

	return fmt.Sprintf(`# %s

A curated collection managed with [shelfctl](https://github.com/blackwell-systems/shelfctl).

## About This Shelf

<!-- Add a description of what this shelf contains -->

Created: %s

## Quick Stats

- **Books**: 0
- **Last Updated**: %s

## Adding Books

Add books to this shelf using:

`+"```"+`bash
shelfctl shelve ~/Downloads/book.pdf --shelf %s --title "Book Title" --author "Author Name"
`+"```"+`

Or use the interactive workflow:

`+"```"+`bash
shelfctl shelve
`+"```"+`

## Browsing

View books in this shelf:

`+"```"+`bash
shelfctl browse --shelf %s
`+"```"+`

## Maintenance

This shelf is managed with shelfctl. The source of truth for metadata is `+"`catalog.yml`"+`.

- **View catalog**: `+"`cat catalog.yml`"+`
- **Validate**: `+"`shelfctl shelves`"+`
- **Split shelf**: `+"`shelfctl split`"+` (when it grows large)

## Links

- [shelfctl Documentation](https://github.com/blackwell-systems/shelfctl)
- [Release Assets](%s)

---

*Generated by shelfctl on %s*
`, shelfName, now, now, shelfName, shelfName,
		fmt.Sprintf("https://github.com/%s/%s/releases", owner, repoName), now)
}

// Wrappers that delegate to operations package (shared with unified TUI)

func updateShelfREADMEStats(existingREADME string, bookCount int) string {
	return operations.UpdateShelfREADMEStats(existingREADME, bookCount)
}

func appendToShelfREADME(existingREADME string, book catalog.Book) string {
	return operations.AppendToShelfREADME(existingREADME, book)
}

func removeFromShelfREADME(existingREADME string, bookID string) string {
	return operations.RemoveFromShelfREADME(existingREADME, bookID)
}
